<?xml version="1.0" encoding="utf-8"?><Database Name="CompDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\CompDB.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CompDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Projects" Member="Projects">
    <Type Name="Projects">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="About" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Tests" Member="Tests">
    <Type Name="Tests">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TestTasks" Member="TestTasks">
    <Type Name="TestTasks">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Quest" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Answers" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TrueAnswer" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Dificult" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Competence" Member="Competence">
    <Type Name="Competence">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.StudyPrograms" Member="StudyPrograms">
    <Type Name="StudyPrograms">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="About" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="StudyForm" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Competence" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PostProfile" Member="PostProfile">
    <Type Name="PostProfile">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Staff" Member="Staff">
    <Type Name="Staff">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FIO" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Post" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>